#!/bin/bash


# check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <filename>"
    exit 1
fi

# Get the filename from the command-line argument
filename=$1

# Check if the file exists
if [ ! -f "$filename" ]; then
    echo "File '$filename' not found."
    exit 1
fi


# Display the first and last 10 lines of the file

echo
echo "----- HEAD ------"
head "$filename"
echo 
echo "------ TAIL ------"
tail "$filename"

